name: Deploy To S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: 의존성 설치
        run: npm install

      - name: build 하기
        run: npm run build
      
      - name: AWS resource에 접근할 수 있게 AWS 인증
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
      - name: S3 기존 파일 삭제
        run:
         aws s3 rm s3://aws-practice-cicd --recursive

      - name: S3에 빌드된 파일 업로드
        run:
          aws s3 cp ./dist s3://aws-practice-cicd/ --recursive
      
      - name: CloudFront 캐시 갱신
        run: aws cloudFront create-invalidation --distribution-id E1KKC6TJTDGGEH --paths "/*"